### ISSUE TITLE
Can't find repository in NPM

### ISSUE THREAD

**Issue by Snowbell92** [silvermine/videojs-chromecast#16]
I tried installing using npm, but the repo was not found. The log shows `error 404 Not Found: silvermine-videojs-chromecast@latest`. Is this plugin maintained anymore?

**Comment by jthomerson** [comment]
We haven't published this module to an NPM repo yet. You can `npm install --save git+https://github.com/silvermine/videojs-chromecast.git#4e10ff306f3a3457bb392c5a841a62df0050ec3f`

**Comment by Snowbell92** [comment]
hi, thanks for getting back. Please edit your `readme` and add a flag that your repository isn't published in NPM yet, because it clearly states that we can install it using NPM. That will remove the confusion for everyone. cheers!

**Comment by jthomerson** [comment]
@Snowbell92 today this plugin was published as `@silvermine/videojs-chromecast@1.0.0`. Sorry about that!

Note a couple things about this release:

 1. It includes a bug fix for #17. If you use jQuery, consult the updated README
 2. It was renamed from `silvermine-videojs-chromecast` to `@silvermine/videojs-chromecast` because we're moving all our modules over to an NPM organization instead of having them published under a single publisher (me).
