### ISSUE TITLE
Not working with the latest Videojs version

### ISSUE THREAD

**Issue by ayDavidGitHere** [silvermine/videojs-chromecast#176]
Casting does not work with the latest videojs version.

**Behaviour**

VideoJs 7.x.x: Chromcast works as expected.
VideoJs 8.10.0: Dark screen on receiver device after connecting.

Sample code: [vjs-chromecast-test](https://codepen.io/aydavid/pen/QWPrPYM?editors=1000)

**Comment by rolandog** [comment]
Oddly enough, the link you're pointing to works for me; I tested on:

- Linux+Chromium
- Android+Chrome

However, the problems I was having were actually due to HLS configuration (I don't know enough yet, but [this solution](https://stackoverflow.com/questions/63172210/chromecast-hls-unable-to-derive-timescale#comment121806244_63172539) (~Removing~ commenting out both `hlsSegmentFormat` and `hlsVideoSegmentFormat` `loadRequest` function modifications) worked for me.

It doesn't work on Firefox, but I've [seen hints](https://old.reddit.com/r/oculus/comments/z8wz1q/is_there_any_technical_reason_why_casting_doesnt/) that it may be due to the lack of native support for Chromecast APIs and the complexities involved in the certification process required by Google.
