### ISSUE TITLE
VTT Support

### ISSUE THREAD

**Issue by eppcqtrwm** [silvermine/videojs-chromecast#29]
Hello,

is there any way to send VTT to Chromecast? because at the moment it seems impossible currently.

Thanks, I'll be grateful if someone can help me to do so

Regards

**Comment by AndrewStobie** [comment]
This is also an issue that I am looking for help on.

**Comment by yokuze** [comment]
Sorry, this plugin does not currently have support for text tracks. We would welcome a pull request that adds support for it.

According to the [Chromecast Advanced Framework](https://developers.google.com/cast/docs/chrome_sender/advanced) documentation,
it should be possible to use VTT text tracks in Chromecast.

The [Chromecast Tech](https://github.com/silvermine/videojs-chromecast/blob/master/src/js/tech/ChromecastTech.js#L177) is responsible for making the media `Load` request talked about in the Chromecast Advanced Framework documentation, so that would be a good starting point to look at for adding support for text tracks.

**Comment by AndrewStobie** [comment]
@yokuze thank you for the leads I will see what I can do.

**Comment by p0rsche** [comment]
Guys, any news about subtitles support?

**Comment by jthomerson** [comment]
@p0rsche since it hasn't been a feature our core team is pursuing, we have not worked on it. You're welcome to submit a PR. @yokuze gave some pointers as to where to get started. Use `grunt standards` to ensure that your code passes our linting rules; PRs get accepted faster when they come in already adhering to our [coding standards](https://github.com/silvermine/silvermine-info/blob/master/coding-standards.md) and [commit history standards](https://github.com/silvermine/silvermine-info/blob/master/commit-history.md).

**Comment by rtkac** [comment]
Hi guys,
is there something new with the subtitles? I can see that it's pushed in the forked repo [locpd/videojs-chromecast](https://github.com/locpd/videojs-chromecast/commit/2e36afeb54ec6f38d4a7f5d02c8d79f3f1ee56f3) but what about this repository?
Thanks a lot!
