### ISSUE TITLE
Shareable links as YouTube not working

### ISSUE THREAD

**Issue by DJ-PD** [silvermine/videojs-chromecast#38]
Made over 30 different tests both via video source element and playlist/playlist Ui/YouTube plugin there the outcome is as below.
NOTE: All videos play as a charm in VideoJS (test made with v7.3.0 and 7.4.1).  Some of bellow mentioned links are examples but you get the point.

***Silvermine Chromecast test via video element link***
`<source src="http://www.caminandes.com/download/03_caminandes_llamigos_1080p.mp4" type="video/mp4">`OK and working
`<source src="https://youtu.be/BS4wTFZBLj0" type="video/youtube">` Not working
`<source src="video/xxxxxx.mp4" type="video/mp4">` Not working
`<source src="https://www.dropbox.com/xxxxxx.mp4?raw=1" type="video/mp4">` OK and working`

***Silvermine Chromecast test via playlist/playlist Ui and YouTube plugin*** 
YouTube
      sources: [
        { src: 'https://youtu.be/ei_5R0CvLm4', type: 'video/youtube' },
      ], Not working

G-Drive
      sources: [
        { src: 'https://drive.google.com/uc?export=download&id=xxxxxxxxxxxxxxxxxxxx', type: 'video/mp4' },
      ], OK and working

OneDrive
      sources: [
        { src: 'https://onedrive.live.com/download?cid=xxxxxxxxxxxxxxxxxxxx', type: 'video/mp4' },
      ], OK and working

Dropbox
      sources: [
        { src: 'https://www.dropbox.com/s/xxxxxxxxxxxxxxxxxxxx/xxx.mp4?raw=1', type: 'video/mp4' },
      ], OK and working

OneDrive (4K larger file)
      sources: [
        { src: 'https://onedrive.live.com/download?cid=xxxxxxxxxxxxxxxxxxxx', type: 'video/mp4' },
      ],  Not working

Caminandes.com
      sources: [
        { src: 'http://www.caminandes.com/download/03_caminandes_llamigos_1080p.mp4', type: 'video/mp4' },
      ], OK and working

Local source
      sources: [
        { src: 'video/xxxx.mp4', type: 'video/mp4' }
      ], Not working

**Comment by jthomerson** [comment]
@DJ-PD Is it possible for you to provide a [minimal, complete, verifiable example (MCVE)](https://stackoverflow.com/help/mcve)? You can look at some of the other issues in this project where you'll see how others have done this with codepens, etc. You also don't give any definition for what "not working" means. You'll need to elaborate.

Frankly, we do not use YouTube videos in our use of the player, so this is not a usecase we've tested. Once you create a MCVE, please post your results and more details. Since YouTube is not a usecase we actively use, this will be low priority for our core team. We'd welcome your investigation, any details you can provide, and a PR if possible.

**Comment by DJ-PD** [comment]
Hi, sorry for being unclear. Not working = video playback not working via Silvermine chromecast script.
In general the script is very good but I am convinced it should be even better and more powerful if  Silvermine chromecast script is compatible with YouTube links and other shareable links. Find attached codepen demo https://codepen.io/DJ-PD/pen/jdWWEg.
Thanks in advance.

**Comment by jthomerson** [comment]
Thanks @DJ-PD. Looks like a good MVCE. If you're able to find the cause of the Chromecast not working with YouTube, please submit more details or a PR.
