### ISSUE TITLE
Is it possible to select audio track in an HLS presentation?

### ISSUE THREAD

**Issue by raestrada95** [silvermine/videojs-chromecast#48]
Hello, I wonder if it is possible to change the audio track if an HLS presentation has two or more types of audio, for example English and Spanish.

**Comment by jthomerson** [comment]
@raestrada95 Is it possible for you to provide a [minimal, complete, verifiable example (MCVE)](https://stackoverflow.com/help/mcve) of using an HLS video that has multiple audio tracks? You can look at some of the other issues in this project where you'll see how others have done this with codepens, etc. Since we don't have any examples of that already, we'd spend more than half our time just trying to set up an example before we could even answer your question. Having that example would allow us to experiment as needed.

**Comment by raestrada95** [comment]
@jthomerson thank you for your answer, of course I leave here an example of an HLS with two types of audio.

https://codepen.io/raestrada/pen/rbZqQG

additional to that example I leave you another live example with the function of being able to change the audio. 

https://videojs.electroteque.org/chromecast

This company has a plugin with interesting functions but it is only for sale. 

I thank you all for this excellent plugin.

**Comment by jthomerson** [comment]
Sorry, @raestrada95, but we do not have time to research adding this feature for you. We are volunteers working on this project for free. Well-written pull requests to add features that show that they have a high quality and are well tested will be accepted if they comply with our [coding standards](https://github.com/silvermine/silvermine-info/blob/master/coding-standards.md), so feel free to submit a pull request if you would like this feature added. Alternatively, you can use paid solutions like the one you linked to.
