### ISSUE TITLE
Not Working with VideoJS 6.13 and VueJS and NuxtJS

### ISSUE THREAD

**Issue by UIX-Design** [silvermine/videojs-chromecast#50]
I am using video.js 6.13.0 inside a nuxt-vue-app. 
Here is my config:

```js
var _video = require('video.js');
require('@silvermine/videojs-airplay')(_video)
require('@silvermine/videojs-chromecast')(_video, { preloadWebComponents: true });

playerOptions: {
               muted: false,
               controls: true,
               techOrder: ['chromecast', 'html5'],
               controlBar: {
                   volumePanel: {
                       inline: false,
                   }
               },
               plugins: {
                   airPlay: {
                      addButtonToControlBar: true 
                   },
                   chromecast: {
                       addButtonToControlBar: true
                   }
               },
               language: 'en',
               sources: [{
                   type: "video/mp4",
                   src: "path/to/video.mp4"
               }],
               //poster : "/static/images/author.jpg",
           }
```
I can't get any issues on the chrome console, but the chromecast button will not be appear in the buttonbar. Where is my issue and how can i solve it?

**Comment by yokuze** [comment]
@UIX-Design Is it possible for you to submit a [minimal, complete, verifiable example (MCVE)](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue? Trying to reproduce the issue in a simplified environment outside of the app that you are writing often makes it easier to determine what the issue is (i.e. a very simple web page with just a Video.js player and the Chromecast plugin).

If you do determine that Vue / Nuxt.js is required to reproduce the issue, perhaps you could use [CodeSandbox](https://codesandbox.io/) for the MCVE. I believe it has support for Nuxt.js.

Also, please note that the Chromecast button will **not** render if there are no Chromecast devices detected on your network. Once a Chromecast device is discoverable on your network, the button should appear.

**Comment by UIX-Design** [comment]
@yokuze please take a look at: https://codesandbox.io/embed/codesandboxnuxt-unme0

**Comment by yokuze** [comment]
@UIX-Design Thank you for the test case. There were several things wrong there.

## Issue 1: Wrong import statement

When I opened the console as you said, I saw the following error:

```
Uncaught TypeError: videojs.getComponent is not a function
    at push../node_modules/@silvermine/videojs-airplay/src/js/components/AirPlayButton.js.module.exports (vendors.app.js:141)
    at push../node_modules/@silvermine/videojs-airplay/src/js/index.js.module.exports (vendors.app.js:291)
    at Module../plugins/nuxt-video-player-plugin.js (app.js:4225)
```

So, I set a breakpoint at `vendors.app.js:141` (which maps to the code in `plugins/nuxt-video-player-plugin.js`) in Chrome's devtools and saw that the value for the `VueVideoPlayer` variable is not `videojs`, as the code expects, but an object with `videojs` on it as a property. 

Therefore, changing `plugins/nuxt-video-player-plugin.js` from:

```js
import Vue from "vue";

const VueVideoPlayer = require("vue-video-player/dist/ssr");
require("@silvermine/videojs-airplay")(VueVideoPlayer);
require("@silvermine/videojs-chromecast")(VueVideoPlayer, {
  preloadWebComponents: true
});
Vue.use(VueVideoPlayer);
```

to

```js
import Vue from "vue";

import VueVideoPlayer, { videojs } from "vue-video-player/dist/ssr";

require("@silvermine/videojs-airplay")(videojs);
require("@silvermine/videojs-chromecast")(videojs, {
  preloadWebComponents: true
});
Vue.use(VueVideoPlayer);
```

Fixes that error.

## Issue 2: Chromecast plugin initialized at the wrong time

The Chromecast plugin is not getting initialized. I'm not going to spend the time to figure out why exactly that is because it's likely because of the timing of when your `nuxt-video-player-plugin.js` file is executed, and when `vue-video-player` actually configures Video.js. However, I did find that initializing the plugin manually inside of the `playerReadied` callback in `index.vue` does initialize the Chromecast player correctly:

```js
    playerReadied(player) {
      player.chromecast({ addButtonToControlBar: true });
      // console.log('example 01: the player is readied', player)
    }
```

### Issue 3: Chromecast Framework was not included

The Chromecast Framework is required for the plugin to work, as the documentation states: https://github.com/silvermine/videojs-chromecast#how-do-i-use-it

I added a `head()` method in `index.vue` to add the script:

```js
head() {
    return {
      script: [
        {
          src:
            "https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"
        }
      ],
    };
  },
```

### Issue 4: No CSS

After fixing issues 1, 2, and 3 above, the Chromecast button appeared, but there was no icon. This is because the plugin's CSS was not included in the demo.



I added a `link` property to the config returned by the new `head()` method to add a link to a CDN hosted version of the stylesheet:

```js
head() {
    return {
      script: [
        {
          src:
            "https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"
        }
      ],
      link: [
        {
          rel: "stylesheet",
          href:
            "https://cdn.jsdelivr.net/npm/@silvermine/videojs-chromecast@1.1.2/dist/silvermine-videojs-chromecast.css"
        }
      ]
    };
  },
```
 
However, ut you should figure out how to pull it in properly from `node_modules/@silvermine/dist/silvermine-videojs-chromecast.css`, along with ``node_modules/@silvermine/dist/images`.


Finally, after correcting these issues, the Chromecast icon appeared:

![image](https://user-images.githubusercontent.com/1326722/58988069-dd65b400-87ae-11e9-9a4f-4558080c18c7.png)

Here's the full working example: https://codesandbox.io/s/codesandboxnuxt-dxylp?fontsize=14
