### ISSUE TITLE
Chromecast and IMA Ads

### ISSUE THREAD

**Issue by jalowin** [silvermine/videojs-chromecast#55]
Hello everybody:

I have a web page and my player and my ads is working but when I try send to the chromecast with the plugin silrvermine-videojs-chromecast the ads play in my browser and the video play in my chromecast and I want that all play it at the chromecast

https://sportsvr.tv

Thanks for all

Best regards

**Comment by jthomerson** [comment]
Sorry, but we do not have the capacity to debug applications for users. If you would like to report a defect or feature request, please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example). Still, we do not promise to implement feature requests because we are volunteers working on this project for free. Well-written pull requests to add features that show that they have a high quality and are well tested will be accepted if they comply with our [coding standards](https://github.com/silvermine/silvermine-info/blob/master/coding-standards.md).

**Comment by jalowin** [comment]
Ok, I dont want that debug my application I only want know that if this plugin can send the ads to chromecast if I use with plugin for videojs videojs-ima

Thanks for all

**Comment by jthomerson** [comment]
@jalowin none of the core devs on this project have used the plugin for ads, so we can't be sure. My guess is that the answer is "no" - that you'd need to do some extra work to support ads.
